### ISSUE TITLE
可以 实现一下 垂直滑动的效果吗？

### ISSUE THREAD

**Issue by yuantanglong** [wangjianxiandev/flutter_story_ui#1]
可以 实现一下 垂直滑动的效果吗？

**Comment by wangjianxiandev** [comment]
> 可以 实现一下 垂直滑动的效果吗？
Ok，请持续关注~

**Comment by yuantanglong** [comment]
> > 可以 实现一下 垂直滑动的效果吗？
> > Ok，请持续关注~

**Comment by yuantanglong** [comment]
能加下我的QQ吗 有问题想请教  429444744

**Comment by yuantanglong** [comment]
> > 可以 实现一下 垂直滑动的效果吗？
> > Ok，请持续关注~

能加下我的QQ吗 有问题想请教 429444744
